"""
ClaudeTaskGenerator — converts ContextPackage into Claude Code task files.

Produces structured Markdown task files that Claude Code can consume
as execution instructions. Each task file contains:
- Module context
- Dependency graph excerpt
- Change information
- Risk assessment
- Execution hints
"""

from __future__ import annotations

import logging
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from lynkmesh_ai.context.schema import ContextPackage, ContextDependency
from lynkmesh_ai.context.formatter import ContextFormatter

logger = logging.getLogger(__name__)

TASK_TEMPLATE = """---
task_id: {task_id}
module: {module}
risk_score: {risk_score}
generated_at: {generated_at}
files_count: {files_count}
deps_count: {deps_count}
---

# Claude Code Task: {module}

## Summary

This task was generated by **LynkMesh AI** for the module `{module}`.

| Property | Value |
|----------|-------|
| **Risk Score** | `{risk_score}` |
| **Files** | {files_count} |
| **Dependencies** | {deps_count} |
| **Generated** | {generated_at} |
| **Changes Detected** | {has_changes} |

{risk_warning}

## Module Context

{module_context}

## Dependency Graph

{dependency_section}

## Files to Review

{files_section}

## Recent Changes

{changes_section}

## Architectural Role

{architectural_role_section}

## Design Patterns

{patterns_section}

## Domain Concepts

{domains_section}

## Architecture Reasoning

{reasoning_section}

## Instructions

{instructions}

## Execution Hooks

{execution_hooks}

---

*Generated by LynkMesh AI v{version}*
"""


class ClaudeTaskGenerator:
    """
    Generates Claude Code task files from ContextPackage objects.

    The output is a structured Markdown file with YAML frontmatter,
    designed to be picked up by Claude Code's task system.
    """

    def __init__(
        self,
        inbox_dir: Optional[Path] = None,
        version: str = "0.1.0",
    ) -> None:
        self.inbox_dir = inbox_dir or Path(".ai/inbox")
        self.inbox_dir = Path(self.inbox_dir)
        self.version = version

    # ------------------------------------------------------------------
    # Task generation
    # ------------------------------------------------------------------

    def generate(
        self,
        pkg: ContextPackage,
        task_id: Optional[str] = None,
        instructions: Optional[str] = None,
        execution_hooks: Optional[List[str]] = None,
    ) -> str:
        """
        Generate a full task Markdown string from a ContextPackage.

        Args:
            pkg: The context package to convert.
            task_id: Unique task ID (auto-generated if not provided).
            instructions: Custom execution instructions.
            execution_hooks: Custom execution hook commands.

        Returns:
            Complete Markdown task file content.
        """
        task_id = task_id or self._generate_task_id(pkg.module)
        generated_at = datetime.now(timezone.utc).isoformat()
        has_changes = "Yes" if pkg.has_changes else "No"

        # Risk warning
        risk_warning = self._risk_warning(pkg.risk_score)

        # Module context narrative
        module_context = self._build_module_context(pkg)

        # Dependency section
        dependency_section = self._build_dependency_section(pkg)

        # Files section
        files_section = self._build_files_section(pkg)

        # Changes section
        changes_section = self._build_changes_section(pkg)

        # Semantic sections
        architectural_role_section = self._build_architectural_role_section(pkg)
        patterns_section = self._build_patterns_section(pkg)
        domains_section = self._build_domains_section(pkg)

        # Reasoning section
        reasoning_section = self._build_reasoning_section(pkg)

        # Instructions
        instructions = instructions or self._default_instructions(pkg)

        # Execution hooks
        hooks = execution_hooks or self._default_hooks(pkg)
        execution_hooks_str = "\n".join(f"- `{h}`" for h in hooks) if hooks else "*None configured*"

        task_content = TASK_TEMPLATE.format(
            task_id=task_id,
            module=pkg.module,
            risk_score=pkg.risk_score,
            generated_at=generated_at,
            files_count=pkg.file_count,
            deps_count=pkg.dependency_count,
            has_changes=has_changes,
            risk_warning=risk_warning,
            module_context=module_context,
            dependency_section=dependency_section,
            files_section=files_section,
            changes_section=changes_section,
            architectural_role_section=architectural_role_section,
            patterns_section=patterns_section,
            domains_section=domains_section,
            reasoning_section=reasoning_section,
            instructions=instructions,
            execution_hooks=execution_hooks_str,
            version=self.version,
        )

        return task_content

    def generate_and_save(
        self,
        pkg: ContextPackage,
        task_id: Optional[str] = None,
        instructions: Optional[str] = None,
        execution_hooks: Optional[List[str]] = None,
    ) -> Path:
        """
        Generate a task file and save it to the inbox.

        Args:
            pkg: The context package.
            task_id: Unique task ID.
            instructions: Custom instructions.
            execution_hooks: Custom execution hooks.

        Returns:
            Path to the written task file.
        """
        task_id = task_id or self._generate_task_id(pkg.module)
        content = self.generate(pkg, task_id, instructions, execution_hooks)

        file_name = f"task_{task_id}.md"
        file_path = self.inbox_dir / file_name

        self.inbox_dir.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")

        logger.info(f"Task file written: {file_path}")
        return file_path

    # ------------------------------------------------------------------
    # Batch generation
    # ------------------------------------------------------------------

    def generate_batch(
        self,
        packages: List[ContextPackage],
        common_instructions: Optional[str] = None,
    ) -> List[Path]:
        """
        Generate task files for multiple context packages.

        Returns:
            List of paths to generated task files.
        """
        paths = []
        for pkg in packages:
            path = self.generate_and_save(
                pkg,
                instructions=common_instructions,
            )
            paths.append(path)
        return paths

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _generate_task_id(self, module_name: str) -> str:
        """Generate a unique task ID from module name and timestamp."""
        ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        safe_name = module_name.replace(".", "-").replace("/", "-")
        return f"{safe_name}_{ts}"

    def _risk_warning(self, risk_score: str) -> str:
        """Return a warning block for high-risk modules."""
        warnings = {
            "critical": (
                "> ⚠️ **CRITICAL RISK** — This module has extensive downstream dependents. "
                "Changes here may cascade across the system. Review all dependents carefully "
                "and ensure comprehensive testing before merging."
            ),
            "high": (
                "> ⚠️ **HIGH RISK** — This module has significant downstream impact. "
                "Thorough testing of dependents is strongly recommended."
            ),
            "medium": (
                "> ⚡ **MEDIUM RISK** — This module has moderate downstream impact. "
                "Verify dependent modules after changes."
            ),
            "low": (
                "> ℹ️ **LOW RISK** — This module has limited downstream impact."
            ),
        }
        return warnings.get(risk_score, "")

    def _build_module_context(self, pkg: ContextPackage) -> str:
        """Build a narrative description of the module context."""
        lines = []
        if pkg.files:
            primary = pkg.files[0]
            if primary.docstring:
                lines.append(f'*"{primary.docstring}"*')
                lines.append("")
            if primary.classes:
                lines.append(f"This module defines **{len(primary.classes)} class(es)**: "
                           f"{', '.join(f'`{c}`' for c in primary.classes)}.")
            if primary.functions:
                lines.append(f"It exports **{len(primary.functions)} function(s)**: "
                           f"{', '.join(f'`{f}`' for f in primary.functions)}.")

        if not lines:
            lines.append(f"This is a module with {pkg.file_count} file(s) "
                         f"and {pkg.dependency_count} dependency relationships.")

        return "\n".join(lines)

    def _build_dependency_section(self, pkg: ContextPackage) -> str:
        """Build the dependency graph section."""
        if not pkg.dependencies:
            return "_No dependencies recorded._"

        # Group by relation type
        imports = [d for d in pkg.dependencies if d.relation_type == "import"]
        calls = [d for d in pkg.dependencies if d.relation_type == "call"]

        lines = []

        if imports:
            lines.append("### Imports")
            lines.append("")
            for dep in imports[:20]:
                lines.append(f"- `{dep.source}` → `{dep.target}`")
            if len(imports) > 20:
                lines.append(f"- ... and {len(imports) - 20} more")
            lines.append("")

        if calls:
            lines.append("### Function Calls")
            lines.append("")
            for dep in calls[:20]:
                lines.append(f"- `{dep.source}` calls `{dep.target}`")
            if len(calls) > 20:
                lines.append(f"- ... and {len(calls) - 20} more")
            lines.append("")

        return "\n".join(lines)

    def _build_files_section(self, pkg: ContextPackage) -> str:
        """Build the files listing section."""
        if not pkg.files:
            return "_No files in package._"

        lines = []
        for f in pkg.files:
            lines.append(f"### `{f.module_name}`")
            lines.append(f"- **Path:** `{f.path}`")
            lines.append(f"- **Lines of Code:** {f.lines_of_code}")
            if f.classes:
                lines.append(f"- **Classes:** {', '.join(f'`{c}`' for c in f.classes)}")
            if f.functions:
                lines.append(f"- **Functions:** {', '.join(f'`{fn}`' for fn in f.functions)}")
            if f.imports:
                imp_list = f.imports[:8]
                suffix = f", ... (+{len(f.imports) - 8} more)" if len(f.imports) > 8 else ""
                lines.append(f"- **Imports:** {', '.join(f'`{i}`' for i in imp_list)}{suffix}")
            lines.append("")
        return "\n".join(lines)

    def _build_changes_section(self, pkg: ContextPackage) -> str:
        """Build the recent changes section."""
        if not pkg.recent_changes:
            return "_No recent changes detected._"

        lines = ["The following changes have been detected:", ""]
        for ch in pkg.recent_changes:
            lines.append(f"- **{ch.change_type.upper()}** `{ch.file_path}`")
            if ch.lines_added or ch.lines_removed:
                lines.append(f"  - Lines: +{ch.lines_added}/-{ch.lines_removed}")
            if ch.commit_hash:
                lines.append(f"  - Commit: `{ch.commit_hash[:8]}`")
        return "\n".join(lines)

    def _default_instructions(self, pkg: ContextPackage) -> str:
        """Generate default execution instructions based on the package."""
        instructions = [
            f"1. Review the dependency graph for `{pkg.module}` to understand its role in the system.",
        ]

        if pkg.recent_changes:
            instructions.append(
                "2. Examine the recent changes listed above. "
                "These changes are the primary reason this task was generated."
            )
            instructions.append(
                "3. Verify that the changes are consistent with the module's documented behavior."
            )
            offset = 3
        else:
            instructions.append(
                "2. Analyze the module for potential improvements, bugs, or missing tests."
            )
            offset = 2

        if pkg.dependencies:
            instructions.append(
                f"{offset + 1}. Check that all dependent modules are compatible with any proposed changes."
            )
            instructions.append(
                f"{offset + 2}. Run existing tests for this module and its dependents."
            )

        if pkg.risk_score in ("high", "critical"):
            instructions.append(
                f"\n** ⚠️  This is a {pkg.risk_score}-risk change.** "
                "Create a rollback plan before proceeding."
            )

        return "\n".join(instructions)

    def _default_hooks(self, pkg: ContextPackage) -> List[str]:
        """Generate default execution hook commands."""
        hooks = []
        if pkg.files:
            # Suggest running the module's tests
            test_path = pkg.files[0].module_name.replace(".", "/")
            hooks.append(f"python -m pytest tests/ -k {pkg.files[0].module_name.split('.')[-1]} -v")
        hooks.append("lynkmesh-ai run --verify")
        return hooks

    # ------------------------------------------------------------------
    # Semantic section builders
    # ------------------------------------------------------------------

    def _build_architectural_role_section(self, pkg: ContextPackage) -> str:
        """Build the architectural role Markdown section."""
        if not pkg.architectural_role:
            return "_No architectural role classified. Run with `--semantic` to enable role analysis._"

        role = pkg.architectural_role
        role_descriptions = {
            "controller": "Handles request routing and input processing",
            "service": "Contains core business logic",
            "repository": "Manages data access and persistence",
            "model": "Defines data entities and DTOs",
            "config": "Configuration and settings management",
            "utility": "Shared helper functions and utilities",
            "interface": "Defines abstract contracts and protocols",
            "middleware": "Processing pipeline interceptors",
            "adapter": "External system integration layer",
            "factory": "Object creation and dependency injection",
            "cli": "Command-line interface and scripting",
        }
        desc = role_descriptions.get(role, f"Classified as `{role}`")
        return f"**Role:** `{role}` — {desc}"

    def _build_patterns_section(self, pkg: ContextPackage) -> str:
        """Build the design patterns Markdown section."""
        if not pkg.design_patterns:
            return "_No design patterns detected. Run with `--semantic` to enable pattern analysis._"

        lines = ["The following design patterns were detected in this module:", ""]
        for p in pkg.design_patterns:
            pattern = p.get("pattern", "?")
            cls = p.get("class_name", "")
            conf = p.get("confidence", 0)
            evidence = p.get("evidence", [])
            cls_str = f" (class: `{cls}`)" if cls else ""
            lines.append(f"- **{pattern}**{cls_str} — confidence: {conf:.0%}")
            for e in evidence[:3]:
                lines.append(f"  - {e}")
        return "\n".join(lines)

    def _build_domains_section(self, pkg: ContextPackage) -> str:
        """Build the domain concepts Markdown section."""
        if not pkg.domain_concepts:
            return "_No domain concepts extracted. Run with `--semantic` to enable domain analysis._"

        lines = ["The following domain concepts are associated with this module:", ""]
        for d in pkg.domain_concepts:
            concept = d.get("concept", "?")
            lines.append(f"- `{concept}`")
        return "\n".join(lines)

    def _build_reasoning_section(self, pkg: ContextPackage) -> str:
        """Build the architecture reasoning Markdown section."""
        if not pkg.reasoning:
            return (
                "_No architecture reasoning available. "
                "Run with `--reason` to enable architectural reasoning._"
            )

        lines: List[str] = []

        # Architecture narrative
        narrative = pkg.reasoning.get("architecture_narrative", "")
        if narrative:
            lines.append("### Architecture Assessment")
            lines.append("")
            lines.append(narrative)
            lines.append("")

        # Risk assessment
        risk = pkg.reasoning.get("risk", {})
        if risk:
            lines.append("### Risk Assessment")
            lines.append("")
            overall = risk.get("overall_level", "unknown")
            score = risk.get("overall_score", 0)
            lines.append(f"**Overall Risk:** `{overall}` (score: {score:.2f})")
            lines.append("")
            factors = risk.get("risk_factors", [])
            if factors:
                lines.append("**Key Risk Factors:**")
                for f in factors:
                    lines.append(f"- {f}")
                lines.append("")
            mitigating = risk.get("mitigating_factors", [])
            if mitigating:
                lines.append("**Mitigating Factors:**")
                for m in mitigating:
                    lines.append(f"- {m}")
                lines.append("")

        # Recommendations
        recs = pkg.reasoning.get("recommendations", [])
        if recs:
            lines.append("### Recommended Actions")
            lines.append("")
            for r in recs:
                priority = r.get("priority", "?")
                title = r.get("title", "?")
                rationale = r.get("rationale", "")
                lines.append(f"- **[{priority.upper()}]** {title}")
                if rationale:
                    lines.append(f"  - {rationale[:150]}")
            lines.append("")

        if not lines:
            return "_No reasoning data available for this module._"

        return "\n".join(lines)
